# Generated by Django 3.1.2 on 2020-10-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('designer', models.CharField(max_length=100)),
                ('pub_year', models.IntegerField()),
            ],
        ),
    ]
