# Generated by Django 3.1.2 on 2020-10-07 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('num_players', models.CharField(choices=[('1', '1 player'), ('2', '2 players'), ('3', '3 players'), ('4', '4 players'), ('5', '5 players'), ('6', '6 players'), ('7', '7 players'), ('8', '8 players'), ('+', 'More than 8 players')], default='1', max_length=1, verbose_name='Number of Players')),
                ('rating', models.CharField(choices=[('1', '1 star'), ('2', '2 stars'), ('3', '3 stars'), ('4', '4 stars'), ('5', '5 stars')], default='3', max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.game')),
            ],
        ),
    ]
